# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: craft-template

# The type of the application to build.
type: php:8.2
build:
    flavor: composer

variables:
    env:
      # Fill these in to keep APP ID and Security Key consistent across platform.sh environments
      CRAFT_APP_ID: ""
      CRAFT_SECURITY_KEY: ""

    php:
        display_errors: On
        error_level: 32767

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
# More info:
hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
      # this is where we build scripts etc
    deploy: |
      echo "Running outstanding migrations before config sync..."
      if ! ./craft migrate/all --interactive=0 ; then
          echo "Pre-migration sync failed. Moving on..."
      fi

      echo "Running Project Config Sync..."
      ./craft project-config/apply
      
      echo "Running outstanding migrations post config sync..."
      ./craft migrate/all --interactive=0 

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'mysqldb:mysql'

# The size of the persistent disk of the application (in MB).
disk: 512

# The mounts that will be performed when the package is deployed.
mounts:
    # Storage for Craft-writeable files.
    "/storage": "shared:files/storage"
    "/web/cpresources": "shared:files/cpresources"
    # Volumes Folder for uploads etc
    "/volumes": "shared:files/volumes"


# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
        # Example: Cache Uploaded images in the browser for 2 weeks.
        "/images":
          allow: true
          expires: 2w
          root: "web/images"

