fieldLayouts:
  54cc10d4-8c8b-4b50-8d04-9eb485ad2948:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cf563932-7417-4fc3-8f91-f6a98f4e11fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11f58f37-bb3b-4e31-9f68-0f279f57f9a8
        userCondition: null
fs: formUploads
handle: formUploads
name: 'Form Uploads'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
