columnSuffix: null
contentColumnType: string
fieldGroup: 0987b3e4-95ff-4979-bb88-d68911548fdd # Common
handle: testImageField
instructions: null
name: ' Test Image Field'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:c812fea5-f86d-4314-b3b8-1d5a29ab088a' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:c812fea5-f86d-4314-b3b8-1d5a29ab088a' # Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:c812fea5-f86d-4314-b3b8-1d5a29ab088a' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
